### ISSUE TITLE
Handle `0x` prefix `str` for `Address`

### ISSUE THREAD

**Issue by yanganto** [second-state/SewUp#223]
Currently, `Address` type can use [from_str](https://github.com/second-state/SewUp/blob/main/sewup/src/types/address.rs#L84) to build the instance, for example.
```rust
let charman_address = Address::from_str("8663DBF0cC68AaF37fC8BA262F2df4c666a41993")?;
```
The API just fit and easily for the developer using web3.js before.

And there is a similar another API in Rust crate `web3`.
```rust
let charman_address = Address::from_str("0x8663DBF0cC68AaF37fC8BA262F2df4c666a41993")?;
```
So it is good to make this the `0x` prefix input also work in sewup, such that developer can use this much easier.

**Comment by carlosfrodrigues** [comment]
I can take this issue! Can you assign this for me?
