### ISSUE TITLE
The ERC 20 examples doesn't support `0x`

### ISSUE THREAD

**Issue by alabulei1** [second-state/SewUp#270]
I want to deploy the erc20 token smart contracts via SewUp with my own address replacing the address in erc20-examples. 
I copied my `0xxxxxxxxxxxxxx`  address copied from MetaMask, then `cargo sewup` failed. So I tried to delete `0x`, then `cargo sewup` successes.

**Comment by yanganto** [comment]
Thanks for reporting this, this will be fixed before next release.
